[DOC-640] Migrate Marketplace EQP guide
AdobeDocs/commerce-marketplace pull request #9
Opened 2022-04-01 17:31 UTC by keharper

## Purpose of this pull request

This pull request (PR) migrates the content of the Marketplace EQP API Guide to the `commerce-marketplace` repo, per https://jira.corp.magento.com/browse/DOC-640

## Affected pages

-  All

## Links to related PRs or Jira tickets

-  ...

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My changes follow the code style of this project.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] All new and existing tests passed.

2022-04-01 19:20 UTC, jeff-matthews requested changes
I'm not sure what to do with the [packages table ](https://developer-stage.adobe.com/commerce/marketplace/guides/eqp/v1/packages/#package-fields).

The only options I can think of are to:

- Convert to HTML and try setting narrow column widths
- Move the table to a separate page that uses a full-width layout and link to it
- Ask the [adobe/aio-theme](https://github.com/adobe/aio-theme) maintainers what they recommend

2022-04-01 19:20 UTC, jeff-matthews commented on src/pages/guides/eqp/v1/access-keys.md
> +**Session tokens** generated in the **sandbox** are separate from those generated in **production**.
This isn't rendering the way I think you want it to.

![Screen Shot 2022-04-01 at 2 10 48 PM](https://user-images.githubusercontent.com/13662379/161326822-5f0cfb53-e90f-4311-93e3-9ce2d0780672.png)

2022-04-01 19:20 UTC, jeff-matthews commented on src/pages/guides/eqp/v1/packages.md
> +|in_progress|string|The submission is in the EQP pipeline. Refer to the `technical` and `marketing` status for more details.|
```suggestion
|`in_progress`|string|The submission is in the EQP pipeline. Refer to the `technical` and `marketing` status for more details.|
```

2022-04-01 19:20 UTC, jeff-matthews commented on src/pages/guides/eqp/v1/packages.md
> +All `action` fields are optional. If not specified, `draft` is the default value.
The backticks aren't rendering code format...

![Screen Shot 2022-04-01 at 2 15 23 PM](https://user-images.githubusercontent.com/13662379/161327437-31aa7fdd-0841-4462-bb94-2782210fcadd.png)

2022-04-04 21:59 UTC, keharper commented
I went with option 4: blow it all up. 

The entries in the first column of the table are now individual h3 or h4s, while the last two columns were transformed into descriptions. The middle 4 columns still exist as a lot of individual 1-row tables.

The descriptions for some of the more complex fields in the original table linked to sections that provided code samples and/or more detailed explanations. These have been merged into the new h3/h4 sections.

Before:
![Screen Shot 2022-04-04 at 4 58 38 PM](https://user-images.githubusercontent.com/11652541/161639181-988e7b93-2f6f-4483-9b35-b2e3d878d99b.png)

After:
![Screen Shot 2022-04-04 at 4 57 50 PM](https://user-images.githubusercontent.com/11652541/161639220-7272e036-1a55-410e-8ac1-ca7387bfd38d.png)





Review: 
https://developer-stage.adobe.com/commerce/marketplace/guides/eqp/v1/packages/

2022-04-05 13:42 UTC, jeff-matthews approved these changes

2022-04-13 14:42 UTC, merged